name: Valgrind workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependency
        run: |
          sudo apt-get -y install valgrind
          sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
      - name: make project
        run: |
          cd Chat-Application-MiniProjectC-/3_Implementation/src
          gcc server.c -c
          gcc client.c -c  
          valgrind ./Chat-Application-MiniProjectC-/3_Implementation/src/server.out
          valgrind ./Chat-Application-MiniProjectC-/3_Implementation/src/client.out
